// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: comunication.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages from Director to Jugador
type ActNow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActNow bool `protobuf:"varint,1,opt,name=act_now,json=actNow,proto3" json:"act_now,omitempty"` // Director tells the player when to act
}

func (x *ActNow) Reset() {
	*x = ActNow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comunication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActNow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActNow) ProtoMessage() {}

func (x *ActNow) ProtoReflect() protoreflect.Message {
	mi := &file_comunication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActNow.ProtoReflect.Descriptor instead.
func (*ActNow) Descriptor() ([]byte, []int) {
	return file_comunication_proto_rawDescGZIP(), []int{0}
}

func (x *ActNow) GetActNow() bool {
	if x != nil {
		return x.ActNow
	}
	return false
}

type PlayerAlive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerAlive bool `protobuf:"varint,1,opt,name=player_alive,json=playerAlive,proto3" json:"player_alive,omitempty"` // Director informs if the player is alive
}

func (x *PlayerAlive) Reset() {
	*x = PlayerAlive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comunication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAlive) ProtoMessage() {}

func (x *PlayerAlive) ProtoReflect() protoreflect.Message {
	mi := &file_comunication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAlive.ProtoReflect.Descriptor instead.
func (*PlayerAlive) Descriptor() ([]byte, []int) {
	return file_comunication_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerAlive) GetPlayerAlive() bool {
	if x != nil {
		return x.PlayerAlive
	}
	return false
}

// Message to send an int between 1, 2, and 3
type OptionMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Option int32 `protobuf:"varint,1,opt,name=option,proto3" json:"option,omitempty"` // Sends an int between 1, 2, and 3
}

func (x *OptionMessage) Reset() {
	*x = OptionMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comunication_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionMessage) ProtoMessage() {}

func (x *OptionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_comunication_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionMessage.ProtoReflect.Descriptor instead.
func (*OptionMessage) Descriptor() ([]byte, []int) {
	return file_comunication_proto_rawDescGZIP(), []int{2}
}

func (x *OptionMessage) GetOption() int32 {
	if x != nil {
		return x.Option
	}
	return 0
}

// Message to send a letter A or B
type LetterMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Letter string `protobuf:"bytes,1,opt,name=letter,proto3" json:"letter,omitempty"` // Sends a letter A or B
}

func (x *LetterMessage) Reset() {
	*x = LetterMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comunication_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LetterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LetterMessage) ProtoMessage() {}

func (x *LetterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_comunication_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LetterMessage.ProtoReflect.Descriptor instead.
func (*LetterMessage) Descriptor() ([]byte, []int) {
	return file_comunication_proto_rawDescGZIP(), []int{3}
}

func (x *LetterMessage) GetLetter() string {
	if x != nil {
		return x.Letter
	}
	return ""
}

// Message to send a string of ints in the format 1,2,3,4,5
type IntStringMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IntString string `protobuf:"bytes,1,opt,name=int_string,json=intString,proto3" json:"int_string,omitempty"` // Sends a string of ints in the format 1,2,3,4,5
}

func (x *IntStringMessage) Reset() {
	*x = IntStringMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comunication_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntStringMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntStringMessage) ProtoMessage() {}

func (x *IntStringMessage) ProtoReflect() protoreflect.Message {
	mi := &file_comunication_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntStringMessage.ProtoReflect.Descriptor instead.
func (*IntStringMessage) Descriptor() ([]byte, []int) {
	return file_comunication_proto_rawDescGZIP(), []int{4}
}

func (x *IntStringMessage) GetIntString() string {
	if x != nil {
		return x.IntString
	}
	return ""
}

// Message to request money from Director to Jugador
type MoneyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Player's name
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MoneyRequest) Reset() {
	*x = MoneyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comunication_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyRequest) ProtoMessage() {}

func (x *MoneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comunication_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyRequest.ProtoReflect.Descriptor instead.
func (*MoneyRequest) Descriptor() ([]byte, []int) {
	return file_comunication_proto_rawDescGZIP(), []int{5}
}

func (x *MoneyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MoneyRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Response for money request from Director to Jugador
type MoneyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int32 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *MoneyResponse) Reset() {
	*x = MoneyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comunication_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoneyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyResponse) ProtoMessage() {}

func (x *MoneyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comunication_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyResponse.ProtoReflect.Descriptor instead.
func (*MoneyResponse) Descriptor() ([]byte, []int) {
	return file_comunication_proto_rawDescGZIP(), []int{6}
}

func (x *MoneyResponse) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_comunication_proto protoreflect.FileDescriptor

var file_comunication_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6f, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x63, 0x69,
	0x6f, 0x6e, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x21, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x4e, 0x6f, 0x77, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x63, 0x74,
	0x5f, 0x6e, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x4e,
	0x6f, 0x77, 0x22, 0x30, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x6c, 0x69, 0x76,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x61, 0x6c, 0x69, 0x76,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41,
	0x6c, 0x69, 0x76, 0x65, 0x22, 0x27, 0x0a, 0x0d, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x27, 0x0a,
	0x0d, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x22, 0x31, 0x0a, 0x10, 0x49, 0x6e, 0x74, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e,
	0x74, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x69, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x3c, 0x0a, 0x0c, 0x4d, 0x6f, 0x6e,
	0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x27, 0x0a, 0x0d, 0x4d, 0x6f, 0x6e, 0x65, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x32, 0xc4, 0x03, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64,
	0x41, 0x63, 0x74, 0x4e, 0x6f, 0x77, 0x12, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x75, 0x6e, 0x69, 0x63,
	0x61, 0x63, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x4e, 0x6f, 0x77, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x44, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x75, 0x6e, 0x69,
	0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x6c, 0x69,
	0x76, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x48, 0x0a, 0x11, 0x53, 0x65,
	0x6e, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x2e, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x48, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x65, 0x74, 0x74,
	0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x75,
	0x6e, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4e,
	0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x75, 0x6e, 0x69, 0x63,
	0x61, 0x63, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x47,
	0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1a,
	0x2e, 0x63, 0x6f, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x6f, 0x6d,
	0x75, 0x6e, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comunication_proto_rawDescOnce sync.Once
	file_comunication_proto_rawDescData = file_comunication_proto_rawDesc
)

func file_comunication_proto_rawDescGZIP() []byte {
	file_comunication_proto_rawDescOnce.Do(func() {
		file_comunication_proto_rawDescData = protoimpl.X.CompressGZIP(file_comunication_proto_rawDescData)
	})
	return file_comunication_proto_rawDescData
}

var file_comunication_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_comunication_proto_goTypes = []interface{}{
	(*ActNow)(nil),           // 0: comunicacion.ActNow
	(*PlayerAlive)(nil),      // 1: comunicacion.PlayerAlive
	(*OptionMessage)(nil),    // 2: comunicacion.OptionMessage
	(*LetterMessage)(nil),    // 3: comunicacion.LetterMessage
	(*IntStringMessage)(nil), // 4: comunicacion.IntStringMessage
	(*MoneyRequest)(nil),     // 5: comunicacion.MoneyRequest
	(*MoneyResponse)(nil),    // 6: comunicacion.MoneyResponse
	(*emptypb.Empty)(nil),    // 7: google.protobuf.Empty
}
var file_comunication_proto_depIdxs = []int32{
	0, // 0: comunicacion.ComunicacionService.SendActNow:input_type -> comunicacion.ActNow
	1, // 1: comunicacion.ComunicacionService.SendPlayerAlive:input_type -> comunicacion.PlayerAlive
	2, // 2: comunicacion.ComunicacionService.SendOptionMessage:input_type -> comunicacion.OptionMessage
	3, // 3: comunicacion.ComunicacionService.SendLetterMessage:input_type -> comunicacion.LetterMessage
	4, // 4: comunicacion.ComunicacionService.SendIntStringMessage:input_type -> comunicacion.IntStringMessage
	5, // 5: comunicacion.ComunicacionService.RequestMoney:input_type -> comunicacion.MoneyRequest
	7, // 6: comunicacion.ComunicacionService.SendActNow:output_type -> google.protobuf.Empty
	7, // 7: comunicacion.ComunicacionService.SendPlayerAlive:output_type -> google.protobuf.Empty
	7, // 8: comunicacion.ComunicacionService.SendOptionMessage:output_type -> google.protobuf.Empty
	7, // 9: comunicacion.ComunicacionService.SendLetterMessage:output_type -> google.protobuf.Empty
	7, // 10: comunicacion.ComunicacionService.SendIntStringMessage:output_type -> google.protobuf.Empty
	6, // 11: comunicacion.ComunicacionService.RequestMoney:output_type -> comunicacion.MoneyResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_comunication_proto_init() }
func file_comunication_proto_init() {
	if File_comunication_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_comunication_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActNow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comunication_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerAlive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comunication_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comunication_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LetterMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comunication_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntStringMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comunication_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoneyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comunication_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoneyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comunication_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comunication_proto_goTypes,
		DependencyIndexes: file_comunication_proto_depIdxs,
		MessageInfos:      file_comunication_proto_msgTypes,
	}.Build()
	File_comunication_proto = out.File
	file_comunication_proto_rawDesc = nil
	file_comunication_proto_goTypes = nil
	file_comunication_proto_depIdxs = nil
}
