// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: comunication.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ComunicacionServiceClient is the client API for ComunicacionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComunicacionServiceClient interface {
	// Director to Jugador communication
	SendActNow(ctx context.Context, in *ActNow, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendPlayerAlive(ctx context.Context, in *PlayerAlive, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Jugador to Director communication
	SendOptionMessage(ctx context.Context, in *OptionMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendLetterMessage(ctx context.Context, in *LetterMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendIntStringMessage(ctx context.Context, in *IntStringMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RequestMoney(ctx context.Context, in *MoneyRequest, opts ...grpc.CallOption) (*MoneyResponse, error)
}

type comunicacionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComunicacionServiceClient(cc grpc.ClientConnInterface) ComunicacionServiceClient {
	return &comunicacionServiceClient{cc}
}

func (c *comunicacionServiceClient) SendActNow(ctx context.Context, in *ActNow, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/comunication.ComunicacionService/SendActNow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comunicacionServiceClient) SendPlayerAlive(ctx context.Context, in *PlayerAlive, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/comunication.ComunicacionService/SendPlayerAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comunicacionServiceClient) SendOptionMessage(ctx context.Context, in *OptionMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/comunication.ComunicacionService/SendOptionMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comunicacionServiceClient) SendLetterMessage(ctx context.Context, in *LetterMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/comunication.ComunicacionService/SendLetterMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comunicacionServiceClient) SendIntStringMessage(ctx context.Context, in *IntStringMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/comunication.ComunicacionService/SendIntStringMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comunicacionServiceClient) RequestMoney(ctx context.Context, in *MoneyRequest, opts ...grpc.CallOption) (*MoneyResponse, error) {
	out := new(MoneyResponse)
	err := c.cc.Invoke(ctx, "/comunication.ComunicacionService/RequestMoney", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComunicacionServiceServer is the server API for ComunicacionService service.
// All implementations must embed UnimplementedComunicacionServiceServer
// for forward compatibility
type ComunicacionServiceServer interface {
	// Director to Jugador communication
	SendActNow(context.Context, *ActNow) (*emptypb.Empty, error)
	SendPlayerAlive(context.Context, *PlayerAlive) (*emptypb.Empty, error)
	// Jugador to Director communication
	SendOptionMessage(context.Context, *OptionMessage) (*emptypb.Empty, error)
	SendLetterMessage(context.Context, *LetterMessage) (*emptypb.Empty, error)
	SendIntStringMessage(context.Context, *IntStringMessage) (*emptypb.Empty, error)
	RequestMoney(context.Context, *MoneyRequest) (*MoneyResponse, error)
	mustEmbedUnimplementedComunicacionServiceServer()
}

// UnimplementedComunicacionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedComunicacionServiceServer struct {
}

func (UnimplementedComunicacionServiceServer) SendActNow(context.Context, *ActNow) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendActNow not implemented")
}
func (UnimplementedComunicacionServiceServer) SendPlayerAlive(context.Context, *PlayerAlive) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPlayerAlive not implemented")
}
func (UnimplementedComunicacionServiceServer) SendOptionMessage(context.Context, *OptionMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOptionMessage not implemented")
}
func (UnimplementedComunicacionServiceServer) SendLetterMessage(context.Context, *LetterMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLetterMessage not implemented")
}
func (UnimplementedComunicacionServiceServer) SendIntStringMessage(context.Context, *IntStringMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendIntStringMessage not implemented")
}
func (UnimplementedComunicacionServiceServer) RequestMoney(context.Context, *MoneyRequest) (*MoneyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestMoney not implemented")
}
func (UnimplementedComunicacionServiceServer) mustEmbedUnimplementedComunicacionServiceServer() {}

// UnsafeComunicacionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComunicacionServiceServer will
// result in compilation errors.
type UnsafeComunicacionServiceServer interface {
	mustEmbedUnimplementedComunicacionServiceServer()
}

func RegisterComunicacionServiceServer(s grpc.ServiceRegistrar, srv ComunicacionServiceServer) {
	s.RegisterService(&ComunicacionService_ServiceDesc, srv)
}

func _ComunicacionService_SendActNow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActNow)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComunicacionServiceServer).SendActNow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comunication.ComunicacionService/SendActNow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComunicacionServiceServer).SendActNow(ctx, req.(*ActNow))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComunicacionService_SendPlayerAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerAlive)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComunicacionServiceServer).SendPlayerAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comunication.ComunicacionService/SendPlayerAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComunicacionServiceServer).SendPlayerAlive(ctx, req.(*PlayerAlive))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComunicacionService_SendOptionMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptionMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComunicacionServiceServer).SendOptionMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comunication.ComunicacionService/SendOptionMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComunicacionServiceServer).SendOptionMessage(ctx, req.(*OptionMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComunicacionService_SendLetterMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LetterMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComunicacionServiceServer).SendLetterMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comunication.ComunicacionService/SendLetterMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComunicacionServiceServer).SendLetterMessage(ctx, req.(*LetterMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComunicacionService_SendIntStringMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntStringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComunicacionServiceServer).SendIntStringMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comunication.ComunicacionService/SendIntStringMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComunicacionServiceServer).SendIntStringMessage(ctx, req.(*IntStringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComunicacionService_RequestMoney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComunicacionServiceServer).RequestMoney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comunication.ComunicacionService/RequestMoney",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComunicacionServiceServer).RequestMoney(ctx, req.(*MoneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ComunicacionService_ServiceDesc is the grpc.ServiceDesc for ComunicacionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComunicacionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "comunication.ComunicacionService",
	HandlerType: (*ComunicacionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendActNow",
			Handler:    _ComunicacionService_SendActNow_Handler,
		},
		{
			MethodName: "SendPlayerAlive",
			Handler:    _ComunicacionService_SendPlayerAlive_Handler,
		},
		{
			MethodName: "SendOptionMessage",
			Handler:    _ComunicacionService_SendOptionMessage_Handler,
		},
		{
			MethodName: "SendLetterMessage",
			Handler:    _ComunicacionService_SendLetterMessage_Handler,
		},
		{
			MethodName: "SendIntStringMessage",
			Handler:    _ComunicacionService_SendIntStringMessage_Handler,
		},
		{
			MethodName: "RequestMoney",
			Handler:    _ComunicacionService_RequestMoney_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comunication.proto",
}
